name: Maven CI - Reusable

on:
  workflow_call:
    inputs:
      java-version:
        description: "JDK version"
        required: false
        default: "17"
        type: string
      artifact-name:
        description: "Name for uploaded JAR artifact"
        required: false
        default: "app-jar"
        type: string
      agent: 
        description: 'List of agents to run the job on'
        required: false
        default: 'ubuntu-latest'
        type: string # string, boolean, or environment

permissions:
  contents: read
  checks: write
  pull-requests: write  

jobs:
  build-test:
    runs-on: ${{ inputs.agent }}

    steps:
      # 1. Checkout
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: temurin
          cache: maven

      # 3. Build & run tests
      - name: Build with Maven
        run: mvn clean verify

      # 4. Publish JUnit test results
      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Maven Unit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      # 5. Upload raw test reports
      - name: Upload JUnit XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: target/surefire-reports/

      # 6. Upload built JAR
      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: target/*.jar
